import { AppProps } from 'next/dist/next-server/lib/router/router';
import '../styles/globals.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }:AppProps ):JSX.Element{
  return (
  <>
  <Head>
  <title>Create Next</title>
  <meta name="description" content="Generated by create next app" />
  <link key={1}  rel="icon" href="/favicon5.ico" />
</Head>
  <Component {...pageProps} />;
  </>);
}

export default MyApp;
